version: '3'

services:  
    nginx:
        image: nginx:latest
        container_name: Nginx-BSBD
        ports:
            - "8890:8890"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
        - web

    web:
        build: 
            context: .
            dockerfile: ./compose/dev/django/Dockerfile
        image: bsbd_django
        command: /start
        depends_on:
            - db1
        volumes:
            - ./src:/src
        expose:
            - "8890"

        env_file:
            - ./src/.envs/.django

    db1:
        image: postgres:latest
        container_name: Postgres-BSBD
        env_file:
            - ./src/.envs/.postgres
        ports:
            - 54322:5432