# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameConnection', models.CharField(max_length=10)),
                ('ConnectionString', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameGroup', models.CharField(max_length=10)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTask', models.CharField(max_length=20)),
                ('TaskText', models.TextField()),
                ('WTask', models.TextField()),
                ('Weight', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('DateActivate', models.DateTimeField()),
                ('Time', models.IntegerField()),
                ('Variants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestConnectDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConnectDataBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.ConnectDataBase')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.IntegerField(blank=True)),
                ('StartTest', models.DateTimeField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant', models.IntegerField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.Task')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='Task',
            field=models.ManyToManyField(through='TestProject.TestTask', to='TestProject.Task'),
        ),
        migrations.AddField(
            model_name='test',
            name='TestPerson',
            field=models.ManyToManyField(through='TestProject.TestPerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='TestTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestProject.TestTask'),
        ),
    ]
