# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Category',
        ),
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.ManyToManyField(to='TestProject.Category'),
        ),
    ]
